name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world-image
          path: .

      - name: Load Docker image
        run: docker load -i hello-world.tar

      - name: Save Docker image to tar
        run: docker save hello-world:latest -o hello-world.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "hello-world.tar"
          target: "~/"

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i ~/hello-world.tar
            docker stop staging-app || true
            docker rm staging-app || true
            docker tag hello-world:latest hello-world:rollback || true
            docker run -d --name staging-app -p 8080:8080 hello-world:latest
            sleep 5
            curl -f http://localhost:8080 || (
              echo "Health check failed, rolling back..." &&
              docker stop staging-app || true &&
              docker rm staging-app || true &&
              docker run -d --name staging-app -p 8080:8080 hello-world:rollback
            )
