name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run dummy tests
        run: |
          echo "Running dummy test..."
          echo "✔ Dummy test passed!"

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.SHORT_SHA }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.SHORT_SHA }} ${{ secrets.DOCKER_USERNAME }}/hello-world:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.SHORT_SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
